version: '3'

services:

        laravel-service:
                build:
                   context: ./laravel
                   dockerfile: Dockerfile.prod
                image: maxkikuchi/laravel:prod
                container_name: laravelmax
                networks:
                        - laranet
        
        nginx:  
                build:
                   context: ./nginx
                   dockerfile: Dockerfile.prod                
                image: maxkikuchi/nginx:prod
                container_name: nginx
                networks:
                        - laranet
                ports:
                        - "8085:80"

networks:
        laranet:
                driver: bridge       