FROM node:latest AS builder

WORKDIR /AppNodeBasico

COPY . .

EXPOSE 3000

ENTRYPOINT [ "node", "index.js" ]

FROM node:20-alpine3.17

WORKDIR /AppNodeBasico

COPY --from=builder /AppNodeBasico .

EXPOSE 3000

ENTRYPOINT [ "node", "index.js" ]