FROM node:latest AS builder

WORKDIR /usr/src/app

COPY . .

EXPOSE 3000

ENTRYPOINT [ "node", "index.js" ]

FROM node:20-alpine3.17

WORKDIR /usr/src/app

RUN npm install mysql --save

COPY --from=builder /usr/src/app .

EXPOSE 3000

ENTRYPOINT [ "node", "index.js" ]